//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GamePlaza.rc
//
#define IDD_GAME_PLAZA                  102
#define IDD_SHORT_MESSAGE               110
#define IDD_FIND_USER                   111
#define IDD_MANAGER_RIGHT               115
#define IDR_MAINFRAME                   128
#define IDS_MAIN_TITLE                  129
#define IDD_GAME_ROOM                   130
#define IDD_LOGON                       132
#define IDR_MENU                        134
#define IDD_CONTROL_BAR                 135
#define IDD_STATUS                      136
#define IDB_CONNECT_STATUS              137
#define IDB_SERVER_LIST_IMAGE           142
#define IDB_USER_STATUS                 144
#define IDB_BT_EXPESSION                147
#define IDB_BT_SEND_CHAT                149
#define IDB_BT_COLOR_SET                150
#define IDB_BT_CLEAN_SCREEN             151
#define IDB_FRAME_MIN                   158
#define IDB_FRAME_CLOSE                 159
#define IDB_BAR_LEFT                    160
#define IDB_BAR_MIN                     161
#define IDB_BAR_RIGHT                   162
#define IDB_BAR_ITEM                    163
#define IDD_OPTION                      181
#define IDB_OP_BACKGROUND               182
#define IDD_OPTION_TABLE_RULE           182
#define IDB_OP_NORMAL                   183
#define IDD_OPTION_SYSTEM               183
#define IDB_OP_HOT                      184
#define IDB_OP_ACTIVE                   185
#define IDB_SERVER_BL                   192
#define IDB_SERVER_BM                   193
#define IDB_SERVER_BR                   194
#define IDB_SERVER_LM                   195
#define IDB_SERVER_RM                   196
#define IDB_SERVER_TL                   197
#define IDB_SERVER_TM                   198
#define IDB_SERVER_TR                   199
#define IDB_WEB_BL                      200
#define IDB_WEB_BM                      201
#define IDB_WEB_BR                      202
#define IDB_WEB_LM                      203
#define IDB_WEB_RM                      204
#define IDB_WEB_TL                      205
#define IDB_WEB_TM                      206
#define IDB_WEB_TR                      207
#define IDB_TABLE_BL                    208
#define IDB_TABLE_BM                    209
#define IDC_HAND_CUR                    209
#define IDB_TABLE_BR                    210
#define IDB_TABLE_LM                    211
#define IDB_TABLE_RM                    212
#define IDB_TABLE_TL                    213
#define IDB_TABLE_TM                    214
#define IDB_TABLE_TR                    215
#define IDB_LEFT_VIEW_LM                216
#define IDB_LEFT_VIEW_MM                217
#define IDB_LEFT_VIEW_RM                218
#define IDB_LEFT_VIEW_LTM               219
#define IDB_LEFT_VIEW_RTM               220
#define IDB_LEFT_VIEW_LT                221
#define IDB_LEFT_VIEW_MT                222
#define IDB_LEFT_VIEW_RT                223
#define IDB_LEFT_VIEW_LB                224
#define IDB_LEFT_VIEW_MB                225
#define IDB_LEFT_VIEW_RB                226
#define IDB_LEFT_VIEW_LBM               227
#define IDB_LEFT_VIEW_RBM               228
#define IDB_TABLE_LOCK                  230
#define IDB_TABLE_READY                 231
#define IDB_FRAME_TL                    241
#define IDB_FRAME_TM                    242
#define IDB_FRAME_TR                    243
#define IDB_BAR_BUTTON                  244
#define IDB_FRAME_L                     245
#define IDB_FRAME_R                     246
#define IDB_FRAME_BT_BUTTON_4           247
#define IDB_FRAME_BT_BUTTON_3           248
#define IDB_FRAME_BT_BUTTON_2           249
#define IDB_FRAME_BT_BUTTON_1           250
#define IDB_BT_SEARCH_USER              251
#define IDB_BT_AUTO_JOIN                252
#define IDB_BAR_BUTTON_FRIEND           253
#define IDB_BAR_BUTTON_QUIT             254
#define IDB_BAR_BUTTON_NUMBER           255
#define IDB_BAR_BUTTON_SET              256
#define IDB_BAR_ITEM_HOME               257
#define IDB_FRAME_BT_BUTTON_5           258
#define IDB_BT_WEB_STOP                 259
#define IDB_LEFT_VIEW_MMM               260
#define IDB_LEFT_VIEW_MTM               261
#define IDD_SEND_WARNING                262
#define IDB_FRAME_BT_BUTTON_6           263
#define IDB_FRAME_BT_BUTTON_7           264
#define IDB_BT_PLAZA_HELP               265
#define IDD_REGISTER                    266
#define IDB_FACE_NORMAL                 267
#define IDD_MANAGER_MESSAGE             267
#define IDD_MANAGER_SERVER              268
#define IDB_BT_WEB_NEXT                 268
#define IDB_BT_WEB_HOME                 269
#define IDB_BT_WEB_BRUSH                270
#define IDB_BT_WEB_BEFORE               271
#define IDD_USER_SHOW                   282
#define IDC_CHAT_MESSAGE                1004
#define IDC_TABLE_PASSWORD              1004
#define IDC_SERVER                      1005
#define IDC_ACCOUNTS                    1006
#define IDC_PASSWORD                    1007
#define IDC_REMEMBER_PASSWORD           1008
#define IDC_DELETE_RECORD               1009
#define IDC_SEND_SHORT                  1010
#define IDC_NET_OPTION                  1011
#define IDC_PASSWORD2                   1011
#define IDC_BIND_USER                   1011
#define IDC_REGISTER                    1012
#define IDC_RECV_MESSAGE                1012
#define IDC_BIND_GAME                   1012
#define IDC_LOGON_TYPE                  1013
#define IDC_SEND_MESSAGE                1013
#define IDC_NAME                        1013
#define IDC_MAIN_PAGE                   1014
#define IDC_ACCID                       1014
#define IDC_PASSWORD_PROTECT            1015
#define IDC_GET_PASSWORD                1016
#define IDC_GET_PASSWORD2               1017
#define IDC_ApplyAccount                1017
#define IDC_PROXY_TYPE                  1018
#define IDC_PROXY_SERVER                1019
#define IDC_PROXY_USER                  1020
#define IDC_PROXY_PORT                  1021
#define IDC_PROXY_PASS                  1022
#define IDC_LIST                        1022
#define IDC_BORDER                      1023
#define IDC_USER_ID                     1024
#define IDC_CLOSE                       1025
#define IDC_TYPE_NAME                   1026
#define IDC_SERVER_LIST                 1027
#define IDC_PLAZA                       1029
#define IDC_BRING_TABLE_PASSWORD        1029
#define IDC_COMPANION_MANAGER           1030
#define IDC_SYSTEM_OPTION               1031
#define IDC_QUIT_GAME                   1034
#define IDC_SWITCH_ACCOUNTS             1036
#define IDC_VOR_SPLITER                 1039
#define IDC_VIEW_ITEM1                  1042
#define IDC_CHAT_INPUT                  1043
#define IDC_VIEW_ITEM2                  1043
#define IDC_VIEW_ITEM3                  1044
#define IDC_AUTO_SIT                    1045
#define IDC_VIEW_ITEM4                  1045
#define IDC_SEND_CHAT                   1046
#define IDC_EXPRESSION                  1047
#define IDC_PHRASE                      1048
#define IDC_COLOR_SET                   1049
#define IDC_CLEAN_SCREEN                1050
#define IDC_FIND_USER                   1051
#define IDC_LIMIT_IP                    1052
#define IDC_LIMIT_FLEE_RATE             1053
#define IDC_FLEE_RATE                   1054
#define IDC_LIMIT_SCORE                 1055
#define IDC_USER_LIST                   1056
#define IDC_LIMIT_NET_DELAY             1056
#define IDC_NET_DELAY                   1057
#define IDC_LIMIT_DETEST                1060
#define IDC_LIMIT_WIN_RATE              1061
#define IDC_WIN_RATE                    1062
#define IDC_SCORE_LESS                  1063
#define IDC_SAVE_NONE                   1065
#define IDC_SAVE_ACCOUNTS               1066
#define IDC_SAVE_ACCOUNTS_AND_PASS      1067
#define IDC_CHAT_OBJECT                 1068
#define IDC_USER_FACE                   1073
#define IDC_PRIVIEW                     1074
#define IDC_WARNING_MESSAGE             1077
#define IDC_ROOM_CHAT                   1078
#define IDC_GAME_MESSAGE                1078
#define IDC_GAME_CHAT                   1079
#define IDC_ROOM_MESSAGE                1079
#define IDC_SEND_WISPER                 1080
#define IDC_SYSTEM_MESSAGE              1080
#define IDC_PLAY_GAME                   1081
#define IDC_LOOKON_GAME                 1082
#define IDC_SET_SHALL_CLOSE             1082
#define IDC_LIMIT_WISPER                1083
#define IDC_BGImage                     1083
#define IDC_LIMIT_ROOM_CHAT             1084
#define IDC_LIMIT_ENTER_GAME            1085
#define IDC_LIMIT_GAME_CHAT             1086
#define IDC_TAB1                        1086
#define IDC_LOGIN_SERVER_LABEL          1086
#define IDC_SCORE_MAX                   1087
#define IDC_LIMIT_ENTER_ROOM            1087
#define IDC_ACCOUNT_LABEL               1087
#define IDC_PASSWORD_LABEL              1088
#define IDC_SHOW_OK                     1089
#define IDC_SHOW_CANCEL                 1090
#define IDC_RESET_SHALL_CLOSE           1094
#define IDC_ALLOW_WISPER                1095
#define IDC_ALLOW_ROOM_CHAT             1096
#define IDC_ALLOW_ENTER_GAME            1097
#define IDC_ALLOW_GAME_CHAT2            1098
#define IDC_ALLOW_GAME_CHAT             1098
#define IDC_ALLOW_ENTER_ROOM            1099
#define IDM_LOGON_PLAZA                 32772
#define IDM_CONNECT_SERVER              32774
#define IDM_CANCEL_CONNECT              32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        283
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
